# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f4d77eb183a949b0897370fac8f334458d3c4c288317efecf7e74e9ebd946f3d8bc6a8a3a368ed142236ab2acd04e2504e8cc408196797f9e8fa16b670bb873

test:
  secret_key_base: 0aaab51f6680602df0664cde4bb50cb1f6f0c5249551f00ec56c8a4294736aed0a98dc15ff4dde24c63eeb20816f770c3d74b995293bc586021cc8630790ace0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
